package cpu

type instruction struct {
	Name   string
	Size   byte
	Cycles byte
	Exec   func(*OpDetails)
	Mode   AddressingMode
}

type OpDetails struct {
	address uint16
	pc      uint16
	mode    AddressingMode
}

// addressing modes
type AddressingMode uint8

const (
	_ AddressingMode = iota
	Absolute
	AbsoluteX
	AbsoluteY
	Accumulator
	Immediate
	Implied
	IndexedIndirect
	Indirect
	IndirectIndexed
	Relative
	ZeroPage
	ZeroPageX
	ZeroPageY
)

var InstructionTable = map[uint8]*instruction{
	0x00: {Name: "BRK", Size: 1, Cycles: 7, Exec: brk, Mode: Implied},
	0x01: {Name: "ORA", Size: 2, Cycles: 6, Exec: ora, Mode: IndexedIndirect},
	0x02: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x03: {Name: "SLO", Size: 2, Cycles: 2, Exec: nop, Mode: IndexedIndirect},
	0x04: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPage},
	0x05: {Name: "ORA", Size: 2, Cycles: 3, Exec: ora, Mode: ZeroPage},
	0x06: {Name: "ASL", Size: 2, Cycles: 5, Exec: asl, Mode: ZeroPage},
	0x07: {Name: "SLO", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPage},
	0x08: {Name: "PHP", Size: 1, Cycles: 3, Exec: php, Mode: Implied},
	0x09: {Name: "ORA", Size: 2, Cycles: 2, Exec: ora, Mode: Immediate},
	0x0a: {Name: "ASL", Size: 1, Cycles: 2, Exec: asl, Mode: Accumulator},
	0x0c: {Name: "NOP", Size: 3, Cycles: 2, Exec: nop, Mode: Absolute},
	0x0d: {Name: "ORA", Size: 3, Cycles: 4, Exec: ora, Mode: Absolute},
	0x0e: {Name: "ASL", Size: 3, Cycles: 6, Exec: asl, Mode: Absolute},
	0x0f: {Name: "SLO", Size: 3, Cycles: 2, Exec: nop, Mode: Absolute},
	0x10: {Name: "BPL", Size: 2, Cycles: 2, Exec: bpl, Mode: Relative},
	0x11: {Name: "ORA", Size: 2, Cycles: 5, Exec: ora, Mode: IndirectIndexed},
	0x12: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x13: {Name: "SLO", Size: 2, Cycles: 2, Exec: nop, Mode: IndirectIndexed},
	0x14: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0x15: {Name: "ORA", Size: 2, Cycles: 4, Exec: ora, Mode: ZeroPageX},
	0x16: {Name: "ASL", Size: 2, Cycles: 6, Exec: asl, Mode: ZeroPageX},
	0x17: {Name: "SLO", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0x18: {Name: "CLC", Size: 1, Cycles: 2, Exec: clc, Mode: Implied},
	0x19: {Name: "ORA", Size: 3, Cycles: 4, Exec: ora, Mode: AbsoluteY},
	0x1a: {Name: "NOP", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x1b: {Name: "SLO", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteY},
	0x1c: {Name: "NOP", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0x1d: {Name: "ORA", Size: 3, Cycles: 4, Exec: ora, Mode: AbsoluteX},
	0x1e: {Name: "ASL", Size: 3, Cycles: 7, Exec: asl, Mode: AbsoluteX},
	0x1f: {Name: "SLO", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0x20: {Name: "JSR", Size: 3, Cycles: 6, Exec: jsr, Mode: Absolute},
	0x21: {Name: "AND", Size: 2, Cycles: 6, Exec: and, Mode: IndexedIndirect},
	0x22: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x23: {Name: "RLA", Size: 2, Cycles: 2, Exec: nop, Mode: IndexedIndirect},
	0x24: {Name: "BIT", Size: 2, Cycles: 3, Exec: bit, Mode: ZeroPage},
	0x25: {Name: "AND", Size: 2, Cycles: 3, Exec: and, Mode: ZeroPage},
	0x26: {Name: "ROL", Size: 2, Cycles: 5, Exec: rol, Mode: ZeroPage},
	0x27: {Name: "RLA", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPage},
	0x28: {Name: "PLP", Size: 1, Cycles: 4, Exec: plp, Mode: Implied},
	0x29: {Name: "AND", Size: 2, Cycles: 2, Exec: and, Mode: Immediate},
	0x2a: {Name: "ROL", Size: 1, Cycles: 2, Exec: rol, Mode: Accumulator},
	0x2c: {Name: "BIT", Size: 3, Cycles: 4, Exec: bit, Mode: Absolute},
	0x2d: {Name: "AND", Size: 3, Cycles: 4, Exec: and, Mode: Absolute},
	0x2e: {Name: "ROL", Size: 3, Cycles: 6, Exec: rol, Mode: Absolute},
	0x2f: {Name: "RLA", Size: 3, Cycles: 2, Exec: nop, Mode: Absolute},
	0x30: {Name: "BMI", Size: 2, Cycles: 2, Exec: bmi, Mode: Relative},
	0x31: {Name: "AND", Size: 2, Cycles: 5, Exec: and, Mode: IndirectIndexed},
	0x32: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x33: {Name: "RLA", Size: 2, Cycles: 2, Exec: nop, Mode: IndirectIndexed},
	0x34: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0x35: {Name: "AND", Size: 2, Cycles: 4, Exec: and, Mode: ZeroPageX},
	0x36: {Name: "ROL", Size: 2, Cycles: 6, Exec: rol, Mode: ZeroPageX},
	0x37: {Name: "RLA", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0x38: {Name: "SEC", Size: 1, Cycles: 2, Exec: sec, Mode: Implied},
	0x39: {Name: "AND", Size: 3, Cycles: 4, Exec: and, Mode: AbsoluteY},
	0x3a: {Name: "NOP", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x3b: {Name: "RLA", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteY},
	0x3c: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0x3d: {Name: "AND", Size: 3, Cycles: 4, Exec: and, Mode: AbsoluteX},
	0x3e: {Name: "ROL", Size: 3, Cycles: 7, Exec: rol, Mode: AbsoluteX},
	0x3f: {Name: "RLA", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0x40: {Name: "RTI", Size: 1, Cycles: 6, Exec: rti, Mode: Implied},
	0x41: {Name: "EOR", Size: 2, Cycles: 6, Exec: eor, Mode: IndexedIndirect},
	0x42: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x43: {Name: "SRE", Size: 2, Cycles: 2, Exec: nop, Mode: IndexedIndirect},
	0x44: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPage},
	0x45: {Name: "EOR", Size: 2, Cycles: 3, Exec: eor, Mode: ZeroPage},
	0x46: {Name: "LSR", Size: 2, Cycles: 5, Exec: lsr, Mode: ZeroPage},
	0x47: {Name: "SRE", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPage},
	0x48: {Name: "PHA", Size: 1, Cycles: 3, Exec: pha, Mode: Implied},
	0x49: {Name: "EOR", Size: 2, Cycles: 2, Exec: eor, Mode: Immediate},
	0x4a: {Name: "LSR", Size: 1, Cycles: 2, Exec: lsr, Mode: Accumulator},
	0x4c: {Name: "JMP", Size: 3, Cycles: 3, Exec: jmp, Mode: Absolute},
	0x4d: {Name: "EOR", Size: 3, Cycles: 4, Exec: eor, Mode: Absolute},
	0x4e: {Name: "LSR", Size: 3, Cycles: 6, Exec: lsr, Mode: Absolute},
	0x4f: {Name: "SRE", Size: 3, Cycles: 2, Exec: nop, Mode: Absolute},
	0x50: {Name: "BVC", Size: 2, Cycles: 2, Exec: bvc, Mode: Relative},
	0x51: {Name: "EOR", Size: 2, Cycles: 5, Exec: eor, Mode: IndirectIndexed},
	0x52: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x53: {Name: "SRE", Size: 2, Cycles: 2, Exec: nop, Mode: IndirectIndexed},
	0x54: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0x55: {Name: "EOR", Size: 2, Cycles: 4, Exec: eor, Mode: ZeroPageX},
	0x56: {Name: "LSR", Size: 2, Cycles: 6, Exec: lsr, Mode: ZeroPageX},
	0x57: {Name: "SRE", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0x58: {Name: "CLI", Size: 1, Cycles: 2, Exec: cli, Mode: Implied},
	0x59: {Name: "EOR", Size: 3, Cycles: 4, Exec: eor, Mode: AbsoluteY},
	0x5a: {Name: "NOP", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x5b: {Name: "SRE", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteY},
	0x5c: {Name: "NOP", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0x5d: {Name: "EOR", Size: 3, Cycles: 4, Exec: eor, Mode: AbsoluteX},
	0x5e: {Name: "LSR", Size: 3, Cycles: 7, Exec: lsr, Mode: AbsoluteX},
	0x5f: {Name: "SRE", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0x60: {Name: "RTS", Size: 1, Cycles: 6, Exec: rts, Mode: Implied},
	0x61: {Name: "ADC", Size: 2, Cycles: 6, Exec: adc, Mode: IndexedIndirect},
	0x62: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x63: {Name: "RRA", Size: 2, Cycles: 2, Exec: nop, Mode: IndexedIndirect},
	0x64: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPage},
	0x65: {Name: "ADC", Size: 2, Cycles: 3, Exec: adc, Mode: ZeroPage},
	0x66: {Name: "ROR", Size: 2, Cycles: 5, Exec: ror, Mode: ZeroPage},
	0x67: {Name: "RRA", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPage},
	0x68: {Name: "PLA", Size: 1, Cycles: 4, Exec: pla, Mode: Implied},
	0x69: {Name: "ADC", Size: 2, Cycles: 2, Exec: adc, Mode: Immediate},
	0x6a: {Name: "ROR", Size: 1, Cycles: 2, Exec: ror, Mode: Accumulator},
	0x6c: {Name: "JMP", Size: 3, Cycles: 5, Exec: jmp, Mode: Indirect},
	0x6d: {Name: "ADC", Size: 3, Cycles: 4, Exec: adc, Mode: Absolute},
	0x6e: {Name: "ROR", Size: 3, Cycles: 6, Exec: ror, Mode: Absolute},
	0x6f: {Name: "RRA", Size: 3, Cycles: 2, Exec: nop, Mode: Absolute},
	0x70: {Name: "BVS", Size: 2, Cycles: 2, Exec: bvs, Mode: Relative},
	0x71: {Name: "ADC", Size: 2, Cycles: 5, Exec: adc, Mode: IndirectIndexed},
	0x72: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x73: {Name: "RRA", Size: 2, Cycles: 2, Exec: nop, Mode: IndirectIndexed},
	0x74: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0x75: {Name: "ADC", Size: 2, Cycles: 4, Exec: adc, Mode: ZeroPageX},
	0x76: {Name: "ROR", Size: 2, Cycles: 6, Exec: ror, Mode: ZeroPageX},
	0x77: {Name: "RRA", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0x78: {Name: "SEI", Size: 1, Cycles: 2, Exec: sei, Mode: Implied},
	0x79: {Name: "ADC", Size: 3, Cycles: 4, Exec: adc, Mode: AbsoluteY},
	0x7a: {Name: "NOP", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x7b: {Name: "RRA", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteY},
	0x7c: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0x7d: {Name: "ADC", Size: 3, Cycles: 4, Exec: adc, Mode: AbsoluteX},
	0x7e: {Name: "ROR", Size: 3, Cycles: 7, Exec: ror, Mode: AbsoluteX},
	0x7f: {Name: "RRA", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0x80: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: Immediate},
	0x81: {Name: "STA", Size: 2, Cycles: 6, Exec: sta, Mode: IndexedIndirect},
	0x82: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: Immediate},
	0x84: {Name: "STY", Size: 2, Cycles: 3, Exec: sty, Mode: ZeroPage},
	0x85: {Name: "STA", Size: 2, Cycles: 3, Exec: sta, Mode: ZeroPage},
	0x86: {Name: "STX", Size: 2, Cycles: 3, Exec: stx, Mode: ZeroPage},
	0x88: {Name: "DEY", Size: 1, Cycles: 2, Exec: dey, Mode: Implied},
	0x89: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: Immediate},
	0x8a: {Name: "TXA", Size: 1, Cycles: 2, Exec: txa, Mode: Implied},
	0x8c: {Name: "STY", Size: 3, Cycles: 4, Exec: sty, Mode: Absolute},
	0x8d: {Name: "STA", Size: 3, Cycles: 4, Exec: sta, Mode: Absolute},
	0x8e: {Name: "STX", Size: 3, Cycles: 4, Exec: stx, Mode: Absolute},
	0x90: {Name: "BCC", Size: 2, Cycles: 2, Exec: bcc, Mode: Relative},
	0x91: {Name: "STA", Size: 2, Cycles: 6, Exec: sta, Mode: IndirectIndexed},
	0x92: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0x94: {Name: "STY", Size: 2, Cycles: 4, Exec: sty, Mode: ZeroPageX},
	0x95: {Name: "STA", Size: 2, Cycles: 4, Exec: sta, Mode: ZeroPageX},
	0x96: {Name: "STX", Size: 2, Cycles: 4, Exec: stx, Mode: ZeroPageY},
	0x98: {Name: "TYA", Size: 1, Cycles: 2, Exec: tya, Mode: Implied},
	0x99: {Name: "STA", Size: 3, Cycles: 5, Exec: sta, Mode: AbsoluteY},
	0x9a: {Name: "TXS", Size: 1, Cycles: 2, Exec: txs, Mode: Implied},
	0x9d: {Name: "STA", Size: 3, Cycles: 5, Exec: sta, Mode: AbsoluteX},
	0xa0: {Name: "LDY", Size: 2, Cycles: 2, Exec: ldy, Mode: Immediate},
	0xa1: {Name: "LDA", Size: 2, Cycles: 6, Exec: lda, Mode: IndexedIndirect},
	0xa2: {Name: "LDX", Size: 2, Cycles: 2, Exec: ldx, Mode: Immediate},
	0xa4: {Name: "LDY", Size: 2, Cycles: 3, Exec: ldy, Mode: ZeroPage},
	0xa5: {Name: "LDA", Size: 2, Cycles: 3, Exec: lda, Mode: ZeroPage},
	0xa6: {Name: "LDX", Size: 2, Cycles: 3, Exec: ldx, Mode: ZeroPage},
	0xa8: {Name: "TAY", Size: 1, Cycles: 2, Exec: tay, Mode: Implied},
	0xa9: {Name: "LDA", Size: 2, Cycles: 2, Exec: lda, Mode: Immediate},
	0xaa: {Name: "TAX", Size: 1, Cycles: 2, Exec: tax, Mode: Implied},
	0xac: {Name: "LDY", Size: 3, Cycles: 4, Exec: ldy, Mode: Absolute},
	0xad: {Name: "LDA", Size: 3, Cycles: 4, Exec: lda, Mode: Absolute},
	0xae: {Name: "LDX", Size: 3, Cycles: 4, Exec: ldx, Mode: Absolute},
	0xb0: {Name: "BCS", Size: 2, Cycles: 2, Exec: bcs, Mode: Relative},
	0xb1: {Name: "LDA", Size: 2, Cycles: 5, Exec: lda, Mode: IndirectIndexed},
	0xb2: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0xb4: {Name: "LDY", Size: 2, Cycles: 4, Exec: ldy, Mode: ZeroPageX},
	0xb5: {Name: "LDA", Size: 2, Cycles: 4, Exec: lda, Mode: ZeroPageX},
	0xb6: {Name: "LDX", Size: 2, Cycles: 4, Exec: ldx, Mode: ZeroPageY},
	0xb8: {Name: "CLV", Size: 1, Cycles: 2, Exec: clv, Mode: Implied},
	0xb9: {Name: "LDA", Size: 3, Cycles: 4, Exec: lda, Mode: AbsoluteY},
	0xba: {Name: "TSX", Size: 1, Cycles: 2, Exec: tsx, Mode: Implied},
	0xbc: {Name: "LDY", Size: 3, Cycles: 4, Exec: ldy, Mode: AbsoluteX},
	0xbd: {Name: "LDA", Size: 3, Cycles: 4, Exec: lda, Mode: AbsoluteX},
	0xbe: {Name: "LDX", Size: 3, Cycles: 4, Exec: ldx, Mode: AbsoluteY},
	0xc0: {Name: "CPY", Size: 2, Cycles: 2, Exec: cpy, Mode: Immediate},
	0xc1: {Name: "CMP", Size: 2, Cycles: 6, Exec: cmp, Mode: IndexedIndirect},
	0xc2: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: Immediate},
	0xc4: {Name: "CPY", Size: 2, Cycles: 3, Exec: cpy, Mode: ZeroPage},
	0xc5: {Name: "CMP", Size: 2, Cycles: 3, Exec: cmp, Mode: ZeroPage},
	0xc6: {Name: "DEC", Size: 2, Cycles: 5, Exec: dec, Mode: ZeroPage},
	0xc8: {Name: "INY", Size: 1, Cycles: 2, Exec: iny, Mode: Implied},
	0xc9: {Name: "CMP", Size: 2, Cycles: 2, Exec: cmp, Mode: Immediate},
	0xca: {Name: "DEX", Size: 1, Cycles: 2, Exec: dex, Mode: Implied},
	0xcc: {Name: "CPY", Size: 3, Cycles: 4, Exec: cpy, Mode: Absolute},
	0xcd: {Name: "CMP", Size: 3, Cycles: 4, Exec: cmp, Mode: Absolute},
	0xce: {Name: "DEC", Size: 3, Cycles: 6, Exec: dec, Mode: Absolute},
	0xd0: {Name: "BNE", Size: 2, Cycles: 2, Exec: bne, Mode: Relative},
	0xd1: {Name: "CMP", Size: 2, Cycles: 5, Exec: cmp, Mode: IndirectIndexed},
	0xd2: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0xd4: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0xd5: {Name: "CMP", Size: 2, Cycles: 4, Exec: cmp, Mode: ZeroPageX},
	0xd6: {Name: "DEC", Size: 2, Cycles: 6, Exec: dec, Mode: ZeroPageX},
	0xd8: {Name: "CLD", Size: 1, Cycles: 2, Exec: cld, Mode: Implied},
	0xd9: {Name: "CMP", Size: 3, Cycles: 4, Exec: cmp, Mode: AbsoluteY},
	0xda: {Name: "NOP", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0xdc: {Name: "NOP", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0xdd: {Name: "CMP", Size: 3, Cycles: 4, Exec: cmp, Mode: AbsoluteX},
	0xde: {Name: "DEC", Size: 3, Cycles: 7, Exec: dec, Mode: AbsoluteX},
	0xe0: {Name: "CPX", Size: 2, Cycles: 2, Exec: cpx, Mode: Immediate},
	0xe1: {Name: "SBC", Size: 2, Cycles: 6, Exec: sbc, Mode: IndexedIndirect},
	0xe2: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: Immediate},
	0xe3: {Name: "ISC", Size: 2, Cycles: 2, Exec: nop, Mode: IndexedIndirect},
	0xe4: {Name: "CPX", Size: 2, Cycles: 3, Exec: cpx, Mode: ZeroPage},
	0xe5: {Name: "SBC", Size: 2, Cycles: 3, Exec: sbc, Mode: ZeroPage},
	0xe6: {Name: "INC", Size: 2, Cycles: 5, Exec: inc, Mode: ZeroPage},
	0xe7: {Name: "ISC", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPage},
	0xe8: {Name: "INX", Size: 1, Cycles: 2, Exec: inx, Mode: Implied},
	0xe9: {Name: "SBC", Size: 2, Cycles: 2, Exec: sbc, Mode: Immediate},
	0xea: {Name: "NOP", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0xec: {Name: "CPX", Size: 3, Cycles: 4, Exec: cpx, Mode: Absolute},
	0xed: {Name: "SBC", Size: 3, Cycles: 4, Exec: sbc, Mode: Absolute},
	0xee: {Name: "INC", Size: 3, Cycles: 6, Exec: inc, Mode: Absolute},
	0xef: {Name: "ISC", Size: 3, Cycles: 2, Exec: nop, Mode: Absolute},
	0xf0: {Name: "BEQ", Size: 2, Cycles: 2, Exec: beq, Mode: Relative},
	0xf1: {Name: "SBC", Size: 2, Cycles: 5, Exec: sbc, Mode: IndirectIndexed},
	0xf2: {Name: "HLT", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0xf3: {Name: "ISC", Size: 2, Cycles: 2, Exec: nop, Mode: IndirectIndexed},
	0xf4: {Name: "NOP", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0xf5: {Name: "SBC", Size: 2, Cycles: 4, Exec: sbc, Mode: ZeroPageX},
	0xf6: {Name: "INC", Size: 2, Cycles: 6, Exec: inc, Mode: ZeroPageX},
	0xf7: {Name: "ISC", Size: 2, Cycles: 2, Exec: nop, Mode: ZeroPageX},
	0xf8: {Name: "SED", Size: 1, Cycles: 2, Exec: sed, Mode: Implied},
	0xf9: {Name: "SBC", Size: 3, Cycles: 4, Exec: sbc, Mode: AbsoluteY},
	0xfa: {Name: "NOP", Size: 1, Cycles: 2, Exec: nop, Mode: Implied},
	0xfb: {Name: "ISC", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteY},
	0xfc: {Name: "NOP", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteX},
	0xfd: {Name: "SBC", Size: 3, Cycles: 4, Exec: sbc, Mode: AbsoluteX},
	0xfe: {Name: "INC", Size: 3, Cycles: 7, Exec: inc, Mode: AbsoluteX},
	0xff: {Name: "ISC", Size: 3, Cycles: 2, Exec: nop, Mode: AbsoluteX},
}
